apiVersion: v1
kind: ConfigMap
metadata:
  name: mxl-gst-testsrc-flow-json
  labels:
    app.kubernetes.io/name: mxl-gst-testsrc
data:
  flow.json: "{\n   \"$copyright\": \"SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.\",\n   \"$license\": \"SPDX-License-Identifier: Apache-2.0\",\n   \"description\": \"___CHANGE ME___ Long description of the video flow\",\n   \"id\": \"5fbec3b1-1b0f-417d-9059-8b94a47197ed\",\n   \"tags\": {\n     \"urn:x-nmos:tag:grouphint/v1.0\": [\n       \"___CHANGE ME FOR A NAME UNIQUE TO YOUR MEDIA FUNCTION INSTANCE___:Video\"\n     ]\n   },\n   \"format\": \"urn:x-nmos:format:video\",\n   \"label\": \"___CHANGE ME___ Short description of the video flow\",\n   \"parents\": [],\n   \"media_type\": \"video/v210\",\n   \"grain_rate\": {\n     \"numerator\": 30000,\n     \"denominator\": 1001\n   },\n   \"frame_width\": 1920,\n   \"frame_height\": 1080,\n   \"interlace_mode\": \"progressive\",\n   \"colorspace\": \"BT709\",\n   \"components\": [\n     {\n       \"name\": \"Y\",\n       \"width\": 1920,\n       \"height\": 1080,\n       \"bit_depth\": 10\n     },\n     {\n       \"name\": \"Cb\",\n       \"width\": 960,\n       \"height\": 1080,\n       \"bit_depth\": 10\n     },\n     {\n       \"name\": \"Cr\",\n       \"width\": 960,\n       \"height\": 1080,\n       \"bit_depth\": 10\n     }\n   ]\n }  \n"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxl-gst-testsrc
  labels:
    app.kubernetes.io/name: mxl-gst-testsrc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mxl-gst-testsrc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mxl-gst-testsrc
    spec:
      nodeSelector:
        mxl.ebu.org/mxl-instance: n0
      volumes:
        - name: flow-config
          configMap:
            name: mxl-gst-testsrc-flow-json
        - name: devshm
          hostPath:
            path: /dev/shm
            type: Directory
      containers:
        - name: mxl-gst-testsrc
          image: docker.io/jonasohland/mxl:v1.1-rc1
          volumeMounts:
            - name: flow-config
              mountPath: /config
            - name: devshm
              mountPath: /dev/shm
          command:
            - /bin/bash
          args:
            - -c
            - |
              #! /bin/bash
              mkdir -p /dev/shm/mxl0
              exec mxl-gst-testsrc -d /dev/shm/mxl0 -v /config/flow.json
